version: "3.1"

services:

  database:
    mem_limit: 2048m
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - ${PMI_PORT}:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - wpsite

  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - ${WP_PORT}:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
    volumes:
      - ./wp-projects/${PROJECT}:/var/www/html
    networks:
      - wpsite
  
volumes:
  db_data:
  wordpress:

networks:
  wpsite:
    driver: bridge